#!/bin/sh

# Install JRuby
wget http://dist.codehaus.org/jruby/1.3.1/jruby-bin-1.3.1.tar.gz
tar xzf jruby-bin-1.3.1.tar.gz
rm jruby-bin-1.3.1.tar.gz
export PATH=`pwd`/jruby-1.3.1/bin:$PATH

# Test that JRuby works
jruby -e "puts 2+2"

# Install Gems needed for Rails and App Engine
jruby -S gem install jruby-openssl rails warbler appengine-apis --no-ri --no-rdoc
jruby -S gem list

# Install App Engine SDK
wget http://googleappengine.googlecode.com/files/appengine-java-sdk-1.2.5.zip
unzip appengine-java-sdk-1.2.5.zip
rm appengine-java-sdk-1.2.5.zip